using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace PersonalFinance.Domain.MccEnum
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum MccCode : int
    {
        [EnumMember(Value = "4814")]
        TelecommunicationServiceIncludingLocalAndLongDistanceCallsCreditCardCallsCallsThroughUseOfMagneticstripReadingTelephonesAndFaxServices = 4814, // Telecommunication service including local and long distance calls, credit card calls, calls through use of magneticstrip reading telephones and fax services
        [EnumMember(Value = "4815")]
        Visaphone = 4815, // VisaPhone
        [EnumMember(Value = "4821")]
        TelegraphServices = 4821, // Telegraph services
        [EnumMember(Value = "4829")]
        MoneyOrdersWireTransfer = 4829, // Money Orders - Wire Transfer
        [EnumMember(Value = "4899")]
        CableAndOtherPayTelevisionPreviouslyCableServices = 4899, // Cable and other pay television (previously Cable Services)
        [EnumMember(Value = "4900")]
        ElectricGasSanitaryAndWaterUtilities = 4900, // Electric, Gas, Sanitary and Water Utilities
        [EnumMember(Value = "5013")]
        MotorVehicleSuppliesAndNewParts = 5013, // Motor vehicle supplies and new parts
        [EnumMember(Value = "5021")]
        OfficeAndCommercialFurniture = 5021, // Office and Commercial Furniture
        [EnumMember(Value = "5039")]
        ConstructionMaterialsNotElsewhereClassified = 5039, // Construction Materials, Not Elsewhere Classified
        [EnumMember(Value = "5044")]
        OfficePhotographicPhotocopyAndMicrofilmEquipment = 5044, // Office, Photographic, Photocopy, and Microfilm Equipment
        [EnumMember(Value = "5045")]
        ComputersComputerPeripheralEquipmentSoftware = 5045, // Computers, Computer Peripheral Equipment, Software
        [EnumMember(Value = "5046")]
        CommercialEquipmentNotElsewhereClassified = 5046, // Commercial Equipment, Not Elsewhere Classified
        [EnumMember(Value = "5047")]
        MedicalDentalOphthalmicHospitalEquipmentAndSupplies = 5047, // Medical, Dental Ophthalmic, Hospital Equipment and Supplies
        [EnumMember(Value = "5051")]
        MetalServiceCentersAndOffices = 5051, // Metal Service Centers and Offices
        [EnumMember(Value = "5065")]
        ElectricalPartsAndEquipment = 5065, // Electrical Parts and Equipment
        [EnumMember(Value = "5072")]
        HardwareEquipmentAndSupplies = 5072, // Hardware Equipment and Supplies
        [EnumMember(Value = "5074")]
        PlumbingAndHeatingEquipmentAndSupplies = 5074, // Plumbing and Heating Equipment and Supplies
        [EnumMember(Value = "5085")]
        IndustrialSuppliesNotElsewhereClassified = 5085, // Industrial Supplies, Not Elsewhere Classified
        [EnumMember(Value = "5094")]
        PreciousStonesAndMetalsWatchesAndJewelry = 5094, // Precious Stones and Metals, Watches and Jewelry
        [EnumMember(Value = "5099")]
        DurableGoodsNotElsewhereClassified = 5099, // Durable Goods, Not Elsewhere Classified
        [EnumMember(Value = "5111")]
        StationeryOfficeSuppliesPrintingAndWritingPaper = 5111, // Stationery, Office Supplies, Printing, and Writing Paper
        [EnumMember(Value = "5122")]
        DrugsDrugProprietorsAndDruggistSSundries = 5122, // Drugs, Drug Proprietors, and Druggists Sundries
        [EnumMember(Value = "5131")]
        PieceGoodsNotionsAndOtherDryGoods = 5131, // Piece Goods, Notions, and Other Dry Goods
        [EnumMember(Value = "5137")]
        MenSWomenSAndChildrenSUniformsAndCommercialClothing = 5137, // Mens Womens and Childrens Uniforms and Commercial Clothing
        [EnumMember(Value = "5139")]
        CommercialFootwear = 5139, // Commercial Footwear
        [EnumMember(Value = "5169")]
        ChemicalsAndAlliedProductsNotElsewhereClassified = 5169, // Chemicals and Allied Products, Not Elsewhere Classified
        [EnumMember(Value = "5172")]
        PetroleumAndPetroleumProducts = 5172, // Petroleum and Petroleum Products
        [EnumMember(Value = "5192")]
        BooksPeriodicalsAndNewspapers = 5192, // Books, Periodicals, and Newspapers
        [EnumMember(Value = "5193")]
        FloristsSuppliesNurseryStockAndFlowers = 5193, // Florists Supplies, Nursery Stock and Flowers
        [EnumMember(Value = "5198")]
        PaintsVarnishesAndSupplies = 5198, // Paints, Varnishes, and Supplies
        [EnumMember(Value = "5199")]
        NonDurableGoodsNotElsewhereClassified = 5199, // Non-durable Goods, Not Elsewhere Classified
        [EnumMember(Value = "5200")]
        HomeSupplyWarehouseStores = 5200, // Home Supply Warehouse Stores
        [EnumMember(Value = "5211")]
        LumberAndBuildingMaterialsStores = 5211, // Lumber and Building Materials Stores
        [EnumMember(Value = "5231")]
        GlassStores = 5231, // Glass Stores
        [EnumMember(Value = "5231")]
        PaintAndWallpaperStores = 5231, // Paint and Wallpaper Stores
        [EnumMember(Value = "5231")]
        WallpaperStores = 5231, // Wallpaper Stores
        [EnumMember(Value = "5251")]
        HardwareStores = 5251, // Hardware Stores
        [EnumMember(Value = "5261")]
        NurseriesLawnAndGardenSupplyStore = 5261, // Nurseries  Lawn and Garden Supply Store
        [EnumMember(Value = "5271")]
        MobileHomeDealers = 5271, // Mobile Home Dealers
        [EnumMember(Value = "5300")]
        WholesaleClubs = 5300, // Wholesale Clubs
        [EnumMember(Value = "5309")]
        DutyFreeStore = 5309, // Duty Free Store
        [EnumMember(Value = "5310")]
        DiscountStores = 5310, // Discount Stores
        [EnumMember(Value = "5311")]
        DepartmentStores = 5311, // Department Stores
        [EnumMember(Value = "5331")]
        VarietyStores = 5331, // Variety Stores
        [EnumMember(Value = "5399")]
        MiscGeneralMerchandise = 5399, // Misc. General Merchandise
        [EnumMember(Value = "5411")]
        GroceryStores = 5411, // Grocery Stores
        [EnumMember(Value = "5411")]
        Supermarkets = 5411, // Supermarkets
        [EnumMember(Value = "5422")]
        FreezerAndLockerMeatProvisioners = 5422, // Freezer and Locker Meat Provisioners
        [EnumMember(Value = "5422")]
        MeatProvisionersFreezerAndLocker = 5422, // Meat Provisioners  Freezer and Locker
        [EnumMember(Value = "5441")]
        CandyStores = 5441, // Candy Stores
        [EnumMember(Value = "5441")]
        ConfectioneryStores = 5441, // Confectionery Stores
        [EnumMember(Value = "5441")]
        NutStores = 5441, // Nut Stores
        [EnumMember(Value = "5451")]
        DairyProductsStores = 5451, // Dairy Products Stores
        [EnumMember(Value = "5462")]
        Bakeries = 5462, // Bakeries
        [EnumMember(Value = "5499")]
        MiscFoodStoresConvenienceStoresAndSpecialtyMarkets = 5499, // Misc. Food Stores  Convenience Stores and Specialty Markets
        [EnumMember(Value = "5511")]
        CarAndTruckDealersNewAndUsedSalesServiceRepairsPartsAndLeasing = 5511, // Car and Truck Dealers (New and Used) Sales, Service, Repairs, Parts, and Leasing
        [EnumMember(Value = "5521")]
        AutomobileAndTruckDealersUsedOnly = 5521, // Automobile and Truck Dealers (Used Only)
        [EnumMember(Value = "5531")]
        AutomobileSupplyStores = 5531, // Automobile Supply Stores
        [EnumMember(Value = "5532")]
        AutomotiveTireStores = 5532, // Automotive Tire Stores
        [EnumMember(Value = "5533")]
        AutomotivePartsAccessoriesStores = 5533, // Automotive Parts, Accessories Stores
        [EnumMember(Value = "5541")]
        ServiceStationsWithOrWithoutAncillaryServices = 5541, // Service Stations ( with or without ancillary services)
        [EnumMember(Value = "5542")]
        AutomatedFuelDispensers = 5542, // Automated Fuel Dispensers
        [EnumMember(Value = "5551")]
        BoatDealers = 5551, // Boat Dealers
        [EnumMember(Value = "5561")]
        RecreationalAndUtilityTrailersCampDealers = 5561, // Recreational and Utility Trailers, Camp Dealers
        [EnumMember(Value = "5571")]
        MotorcycleDealers = 5571, // Motorcycle Dealers
        [EnumMember(Value = "5592")]
        MotorHomeDealers = 5592, // Motor Home Dealers
        [EnumMember(Value = "5598")]
        SnowmobileDealers = 5598, // Snowmobile Dealers
        [EnumMember(Value = "5611")]
        MenSAndBoySClothingAndAccessoriesStores = 5611, // Mens and Boys Clothing and Accessories Stores
        [EnumMember(Value = "5621")]
        WomenSReadyToWearStores = 5621, // Womens Ready - to - Wear Stores
        [EnumMember(Value = "5631")]
        WomenSAccessoryAndSpecialtyShops = 5631, // Womens Accessory and Specialty Shops
        [EnumMember(Value = "5641")]
        ChildrenSAndInfantSWearStores = 5641, // Childrens and Infants Wear Stores
        [EnumMember(Value = "5651")]
        FamilyClothingStores = 5651, // Family Clothing Stores
        [EnumMember(Value = "5655")]
        SportsApparelRidingApparelStores = 5655, // Sports Apparel, Riding Apparel Stores
        [EnumMember(Value = "5661")]
        ShoeStores = 5661, // Shoe Stores
        [EnumMember(Value = "5681")]
        FurriersAndFurShops = 5681, // Furriers and Fur Shops
        [EnumMember(Value = "5691")]
        MenSAndWomenSClothingStores = 5691, // Mens and Womens Clothing Stores
        [EnumMember(Value = "5697")]
        TailorsSeamstressMendingAndAlterations = 5697, // Tailors, Seamstress, Mending, and Alterations
        [EnumMember(Value = "5698")]
        WigAndToupeeStores = 5698, // Wig and Toupee Stores
        [EnumMember(Value = "5699")]
        MiscellaneousApparelAndAccessoryShops = 5699, // Miscellaneous Apparel and Accessory Shops
        [EnumMember(Value = "5712")]
        FurnitureHomeFurnishingsAndEquipmentStoresExceptAppliances = 5712, // Furniture, Home Furnishings, and Equipment Stores, Except Appliances
        [EnumMember(Value = "5713")]
        FloorCoveringStores = 5713, // Floor Covering Stores
        [EnumMember(Value = "5714")]
        DraperyWindowCoveringAndUpholsteryStores = 5714, // Drapery, Window Covering and Upholstery Stores
        [EnumMember(Value = "5718")]
        FireplaceFireplaceScreensAndAccessoriesStores = 5718, // Fireplace, Fireplace Screens, and Accessories Stores
        [EnumMember(Value = "5719")]
        MiscellaneousHomeFurnishingSpecialtyStores = 5719, // Miscellaneous Home Furnishing Specialty Stores
        [EnumMember(Value = "5722")]
        HouseholdApplianceStores = 5722, // Household Appliance Stores
        [EnumMember(Value = "5732")]
        ElectronicSales = 5732, // Electronic Sales
        [EnumMember(Value = "5733")]
        MusicStoresMusicalInstrumentsPianoSheetMusic = 5733, // Music Stores, Musical Instruments, Piano Sheet Music
        [EnumMember(Value = "5734")]
        ComputerSoftwareStores = 5734, // Computer Software Stores
        [EnumMember(Value = "5735")]
        RecordShops = 5735, // Record Shops
        [EnumMember(Value = "5811")]
        Caterers = 5811, // Caterers
        [EnumMember(Value = "5812")]
        EatingPlacesAndRestaurants = 5812, // Eating places and Restaurants
        [EnumMember(Value = "5813")]
        DrinkingPlacesAlcoholicBeveragesBarsTavernsCocktailLoungesNightclubsAndDiscotheques = 5813, // Drinking Places (Alcoholic Beverages), Bars, Taverns, Cocktail lounges, Nightclubs and Discotheques
        [EnumMember(Value = "5814")]
        FastFoodRestaurants = 5814, // Fast Food Restaurants
        [EnumMember(Value = "5912")]
        DrugStoresAndPharmacies = 5912, // Drug Stores and Pharmacies
        [EnumMember(Value = "5921")]
        PackageStoresBeerWineAndLiquor = 5921, // Package Stores - Beer, Wine, and Liquor
        [EnumMember(Value = "5931")]
        UsedMerchandiseAndSecondhandStores = 5931, // Used Merchandise and Secondhand Stores
        [EnumMember(Value = "5832")]
        AntiqueShopsSalesRepairsAndRestorationServices = 5832, // Antique Shops - Sales, Repairs, and Restoration Services
        [EnumMember(Value = "5933")]
        PawnShopsAndSalvageYards = 5933, // Pawn Shops and Salvage Yards
        [EnumMember(Value = "5935")]
        WreckingAndSalvageYards = 5935, // Wrecking and Salvage Yards
        [EnumMember(Value = "5937")]
        AntiqueReproductions = 5937, // Antique Reproductions
        [EnumMember(Value = "5940")]
        BicycleShopsSalesAndService = 5940, // Bicycle Shops - Sales and Service
        [EnumMember(Value = "5941")]
        SportingGoodsStores = 5941, // Sporting Goods Stores
        [EnumMember(Value = "5942")]
        BookStores = 5942, // Book Stores
        [EnumMember(Value = "5943")]
        StationeryStoresOfficeAndSchoolSupplyStores = 5943, // Stationery Stores, Office and School Supply Stores
        [EnumMember(Value = "5944")]
        WatchClockJewelryAndSilverwareStores = 5944, // Watch, Clock, Jewelry, and Silverware Stores
        [EnumMember(Value = "5945")]
        HobbyToyAndGameShops = 5945, // Hobby, Toy, and Game Shops
        [EnumMember(Value = "5946")]
        CameraAndPhotographicSupplyStores = 5946, // Camera and Photographic Supply Stores
        [EnumMember(Value = "5947")]
        CardShopsGiftNoveltyAndSouvenirShops = 5947, // Card Shops, Gift, Novelty, and Souvenir Shops
        [EnumMember(Value = "5948")]
        LeatherFoodsStores = 5948, // Leather Foods Stores
        [EnumMember(Value = "5949")]
        SewingNeedleFabricAndPriceGoodsStores = 5949, // Sewing, Needle, Fabric, and Price Goods Stores
        [EnumMember(Value = "5950")]
        GlasswareCrystalStores = 5950, // Glassware/Crystal Stores
        [EnumMember(Value = "5960")]
        DirectMarketingInsuranceService = 5960, // Direct Marketing - Insurance Service
        [EnumMember(Value = "5961")]
        MailOrderHousesIncludingCatalogOrderStoresBookRecordClubsNoLongerPermittedForSOriginalPresentments = 5961, // Mail Order Houses Including Catalog Order Stores, Book/Record Clubs (No longer permitted for .S. original presentments)
        [EnumMember(Value = "5962")]
        DirectMarketingTravelRelatedArrangementsServices = 5962, // Direct Marketing - Travel Related Arrangements Services
        [EnumMember(Value = "5963")]
        DoorToDoorSales = 5963, // Door - to - Door Sales
        [EnumMember(Value = "5964")]
        DirectMarketingCatalogMerchant = 5964, // Direct Marketing - Catalog Merchant
        [EnumMember(Value = "5965")]
        DirectMarketingCatalogAndCatalogAndRetailMerchantDirectMarketingOutboundTelemarketingMerchant = 5965, // Direct Marketing - Catalog and Catalog and Retail Merchant Direct Marketing - Outbound Telemarketing Merchant
        [EnumMember(Value = "5967")]
        DirectMarketingInboundTeleservicesMerchant = 5967, // Direct Marketing -Inbound Teleservices Merchant
        [EnumMember(Value = "5968")]
        DirectMarketingContinuitySubscriptionMerchant = 5968, // Direct Marketing - Continuity/Subscription Merchant
        [EnumMember(Value = "5969")]
        DirectMarketingNotElsewhereClassified = 5969, // Direct Marketing - Not Elsewhere Classified
        [EnumMember(Value = "5970")]
        ArtistSSupplyAndCraftShops = 5970, // Artists Supply and Craft Shops
        [EnumMember(Value = "5971")]
        ArtDealersAndGalleries = 5971, // Art Dealers and Galleries
        [EnumMember(Value = "5972")]
        StampAndCoinStoresPhilatelicAndNumismaticSupplies = 5972, // Stamp and Coin Stores - Philatelic and Numismatic Supplies
        [EnumMember(Value = "5973")]
        ReligiousGoodsStores = 5973, // Religious Goods Stores
        [EnumMember(Value = "5975")]
        HearingAidsSalesServiceAndSupplyStores = 5975, // Hearing Aids - Sales, Service, and Supply Stores
        [EnumMember(Value = "5976")]
        OrthopedicGoodsProstheticDevices = 5976, // Orthopedic Goods Prosthetic Devices
        [EnumMember(Value = "5977")]
        CosmeticStores = 5977, // Cosmetic Stores
        [EnumMember(Value = "5978")]
        TypewriterStoresSalesRentalService = 5978, // Typewriter Stores - Sales, Rental, Service
        [EnumMember(Value = "5983")]
        FuelFuelOilWoodCoalLiquefiedPetroleum = 5983, // Fuel - Fuel Oil, Wood, Coal, Liquefied Petroleum
        [EnumMember(Value = "5992")]
        Florists = 5992, // Florists
        [EnumMember(Value = "5993")]
        CigarStoresAndStands = 5993, // Cigar Stores and Stands
        [EnumMember(Value = "5994")]
        NewsDealersAndNewsstands = 5994, // News Dealers and Newsstands
        [EnumMember(Value = "5995")]
        PetShopsPetFoodsAndSuppliesStores = 5995, // Pet Shops, Pet Foods, and Supplies Stores
        [EnumMember(Value = "5996")]
        SwimmingPoolsSalesServiceAndSupplies = 5996, // Swimming Pools - Sales, Service, and Supplies
        [EnumMember(Value = "5997")]
        ElectricRazorStoresSalesAndService = 5997, // Electric Razor Stores - Sales and Service
        [EnumMember(Value = "5998")]
        TentAndAwningShops = 5998, // Tent and Awning Shops
        [EnumMember(Value = "5999")]
        MiscellaneousAndSpecialtyRetailStores = 5999, // Miscellaneous and Specialty Retail Stores
        [EnumMember(Value = "6010")]
        FinancialInstitutionsManualCashDisbursements = 6010, // Financial Institutions - Manual Cash Disbursements
        [EnumMember(Value = "6011")]
        FinancialInstitutionsManualCashDisbursements_6011 = 6011, // Financial Institutions - Manual Cash Disbursements
        [EnumMember(Value = "6012")]
        FinancialInstitutionsMerchandiseAndServices = 6012, // Financial Institutions - Merchandise and Services
        [EnumMember(Value = "6051")]
        NonFinancialInstitutionsForeignCurrencyMoneyOrdersNotWireTransferAndTravelersCheques = 6051, // Non - Financial Institutions - Foreign Currency, Money Orders (not wire transfer) and Travelers Cheques
        [EnumMember(Value = "6211")]
        SecurityBrokersDealers = 6211, // Security Brokers/Dealers
        [EnumMember(Value = "6300")]
        InsuranceSalesUnderwritingAndPremiums = 6300, // Insurance Sales, Underwriting, and Premiums
        [EnumMember(Value = "6381")]
        InsurancePremiumsNoLongerValidForFirstPresentmentWork = 6381, // Insurance Premiums, (no longer valid for first presentment work)
        [EnumMember(Value = "6399")]
        InsuranceNotElsewhereClassifiedNoLongerValidForFirstPresentmentWork = 6399, // Insurance, Not Elsewhere Classified ( no longer valid for first presentment work)
        [EnumMember(Value = "7011")]
        LodgingHotelsMotelsResortsCentralReservationServicesNotElsewhereClassified = 7011, // Lodging - Hotels, Motels, Resorts, Central Reservation Services (not elsewhere classified)
        [EnumMember(Value = "7012")]
        Timeshares = 7012, // Timeshares
        [EnumMember(Value = "7032")]
        SportingAndRecreationalCamps = 7032, // Sporting and Recreational Camps
        [EnumMember(Value = "7033")]
        TrailerParksAndCampGrounds = 7033, // Trailer Parks and Camp Grounds
        [EnumMember(Value = "7210")]
        LaundryCleaningAndGarmentServices = 7210, // Laundry, Cleaning, and Garment Services
        [EnumMember(Value = "7211")]
        LaundryFamilyAndCommercial = 7211, // Laundry - Family and Commercial
        [EnumMember(Value = "7216")]
        DryCleaners = 7216, // Dry Cleaners
        [EnumMember(Value = "7217")]
        CarpetAndUpholsteryCleaning = 7217, // Carpet and Upholstery Cleaning
        [EnumMember(Value = "7221")]
        PhotographicStudios = 7221, // Photographic Studios
        [EnumMember(Value = "7230")]
        BarberAndBeautyShops = 7230, // Barber and Beauty Shops
        [EnumMember(Value = "7251")]
        ShopRepairShopsAndShoeShineParlorsAndHatCleaningShops = 7251, // Shop Repair Shops and Shoe Shine Parlors, and Hat Cleaning Shops
        [EnumMember(Value = "7261")]
        FuneralServiceAndCrematories = 7261, // Funeral Service and Crematories
        [EnumMember(Value = "7273")]
        DatingAndEscortServices = 7273, // Dating and Escort Services
        [EnumMember(Value = "7276")]
        TaxPreparationService = 7276, // Tax Preparation Service
        [EnumMember(Value = "7277")]
        CounselingServiceDebtMarriagePersonal = 7277, // Counseling Service - Debt, Marriage, Personal
        [EnumMember(Value = "7278")]
        BuyingShoppingServicesClubs = 7278, // Buying/Shopping Services, Clubs
        [EnumMember(Value = "7296")]
        ClothingRentalCostumesFormalWearUniforms = 7296, // Clothing Rental - Costumes, Formal Wear, Uniforms
        [EnumMember(Value = "7297")]
        MassageParlors = 7297, // Massage Parlors
        [EnumMember(Value = "7298")]
        HealthAndBeautyShops = 7298, // Health and Beauty Shops
        [EnumMember(Value = "7299")]
        MiscellaneousPersonalServicesNotElsewhereClassifies = 7299, // Miscellaneous Personal Services ( not elsewhere classifies)
        [EnumMember(Value = "7311")]
        AdvertisingServices = 7311, // Advertising Services
        [EnumMember(Value = "7321")]
        ConsumerCreditReportingAgencies = 7321, // Consumer Credit Reporting Agencies
        [EnumMember(Value = "7332")]
        BlueprintingAndPhotocopyingServices = 7332, // Blueprinting and Photocopying Services
        [EnumMember(Value = "7333")]
        CommercialPhotographyArtAndGraphics = 7333, // Commercial Photography, Art and Graphics
        [EnumMember(Value = "7338")]
        QuickCopyReproductionAndBlueprintingServices = 7338, // Quick Copy, Reproduction and Blueprinting Services
        [EnumMember(Value = "7339")]
        StenographicAndSecretarialSupportServices = 7339, // Stenographic and Secretarial Support Services
        [EnumMember(Value = "7342")]
        DisinfectingServices = 7342, // Disinfecting Services
        [EnumMember(Value = "7342")]
        ExterminatingAndDisinfectingServices = 7342, // Exterminating and Disinfecting Services
        [EnumMember(Value = "7349")]
        CleaningAndMaintenanceJanitorialServices = 7349, // Cleaning and Maintenance, Janitorial Services
        [EnumMember(Value = "7361")]
        EmploymentAgenciesTemporaryHelpServices = 7361, // Employment Agencies, Temporary Help Services
        [EnumMember(Value = "7372")]
        ComputerProgrammingIntegratedSystemsDesignAndDataProcessingServices = 7372, // Computer Programming, Integrated Systems Design and Data Processing Services
        [EnumMember(Value = "7375")]
        InformationRetrievalServices = 7375, // Information Retrieval Services
        [EnumMember(Value = "7379")]
        ComputerMaintenanceAndRepairServicesNotElsewhereClassified = 7379, // Computer Maintenance and Repair Services, Not Elsewhere Classified
        [EnumMember(Value = "7392")]
        ManagementConsultingAndPublicRelationsServices = 7392, // Management, Consulting, and Public Relations Services
        [EnumMember(Value = "7393")]
        ProtectiveAndSecurityServicesIncludingArmoredCarsAndGuardDogs = 7393, // Protective and Security Services - Including Armored Cars and Guard Dogs
        [EnumMember(Value = "7394")]
        EquipmentRentalAndLeasingServicesToolRentalFurnitureRentalAndApplianceRental = 7394, // Equipment Rental and Leasing Services, Tool Rental, Furniture Rental, and Appliance Rental
        [EnumMember(Value = "7395")]
        PhotofinishingLaboratoriesPhotoDeveloping = 7395, // Photofinishing Laboratories, Photo Developing
        [EnumMember(Value = "7399")]
        BusinessServicesNotElsewhereClassified = 7399, // Business Services, Not Elsewhere Classified
        [EnumMember(Value = "7512")]
        CarRentalCompaniesNotListedBelow = 7512, // Car Rental Companies ( Not Listed Below)
        [EnumMember(Value = "7513")]
        TruckAndUtilityTrailerRentals = 7513, // Truck and Utility Trailer Rentals
        [EnumMember(Value = "7519")]
        MotorHomeAndRecreationalVehicleRentals = 7519, // Motor Home and Recreational Vehicle Rentals
        [EnumMember(Value = "7523")]
        AutomobileParkingLotsAndGarages = 7523, // Automobile Parking Lots and Garages
        [EnumMember(Value = "7531")]
        AutomotiveBodyRepairShops = 7531, // Automotive Body Repair Shops
        [EnumMember(Value = "7534")]
        TireReTreadingAndRepairShops = 7534, // Tire Re - treading and Repair Shops
        [EnumMember(Value = "7535")]
        PaintShopsAutomotive = 7535, // Paint Shops - Automotive
        [EnumMember(Value = "7538")]
        AutomotiveServiceShops = 7538, // Automotive Service Shops
        [EnumMember(Value = "7542")]
        CarWashes = 7542, // Car Washes
        [EnumMember(Value = "7549")]
        TowingServices = 7549, // Towing Services
        [EnumMember(Value = "7622")]
        RadioRepairShops = 7622, // Radio Repair Shops
        [EnumMember(Value = "7623")]
        AirConditioningAndRefrigerationRepairShops = 7623, // Air Conditioning and Refrigeration Repair Shops
        [EnumMember(Value = "7629")]
        ElectricalAndSmallApplianceRepairShops = 7629, // Electrical And Small Appliance Repair Shops
        [EnumMember(Value = "7631")]
        WatchClockAndJewelryRepair = 7631, // Watch, Clock, and Jewelry Repair
        [EnumMember(Value = "7641")]
        FurnitureFurnitureRepairAndFurnitureRefinishing = 7641, // Furniture, Furniture Repair, and Furniture Refinishing
        [EnumMember(Value = "7692")]
        WeldingRepair = 7692, // Welding Repair
        [EnumMember(Value = "7699")]
        RepairShopsAndRelatedServicesMiscellaneous = 7699, // Repair Shops and Related Services - Miscellaneous
        [EnumMember(Value = "7829")]
        MotionPicturesAndVideoTapeProductionAndDistribution = 7829, // Motion Pictures and Video Tape Production and Distribution
        [EnumMember(Value = "7832")]
        MotionPictureTheaters = 7832, // Motion Picture Theaters
        [EnumMember(Value = "7841")]
        VideoTapeRentalStores = 7841, // Video Tape Rental Stores
        [EnumMember(Value = "7911")]
        DanceHallsStudiosAndSchools = 7911, // Dance Halls, Studios and Schools
        [EnumMember(Value = "7922")]
        TheatricalProducersExceptMotionPicturesTicketAgencies = 7922, // Theatrical Producers (Except Motion Pictures), Ticket Agencies
        [EnumMember(Value = "7929")]
        BandsOrchestrasAndMiscellaneousEntertainersNotElsewhereClassified = 7929, // Bands. Orchestras, and Miscellaneous Entertainers (Not Elsewhere Classified)
        [EnumMember(Value = "7932")]
        BilliardAndPoolEstablishments = 7932, // Billiard and Pool Establishments
        [EnumMember(Value = "7933")]
        BowlingAlleys = 7933, // Bowling Alleys
        [EnumMember(Value = "7941")]
        CommercialSportsAthleticFieldsProfessionalSportClubsAndSportPromoters = 7941, // Commercial Sports, Athletic Fields, Professional Sport Clubs, and Sport Promoters
        [EnumMember(Value = "7991")]
        TouristAttractionsAndExhibits = 7991, // Tourist Attractions and Exhibits
        [EnumMember(Value = "7992")]
        GolfCoursesPublic = 7992, // Golf Courses - Public
        [EnumMember(Value = "7993")]
        VideoAmusementGameSupplies = 7993, // Video Amusement Game Supplies
        [EnumMember(Value = "7994")]
        VideoGameArcadesEstablishments = 7994, // Video Game Arcades/Establishments
        [EnumMember(Value = "7995")]
        BettingIncludingLotteryTicketsCasinoGamingChipsOffTrackBettingAndWagers = 7995, // Betting (including Lottery Tickets, Casino Gaming Chips, Off - track Betting and Wagers)
        [EnumMember(Value = "7996")]
        AmusementParksCarnivalsCircusesFortuneTellers = 7996, // Amusement Parks, Carnivals, Circuses, Fortune Tellers
        [EnumMember(Value = "7997")]
        MembershipClubsSportsRecreationAthleticCountryClubsAndPrivateGolfCourses = 7997, // Membership Clubs (Sports, Recreation, Athletic), Country Clubs, and Private Golf Courses
        [EnumMember(Value = "7998")]
        AquariumsSeaAquariumsDolphinariums = 7998, // Aquariums, Sea - aquariums, Dolphinariums
        [EnumMember(Value = "7999")]
        RecreationServicesNotElsewhereClassified = 7999, // Recreation Services (Not Elsewhere Classified)
        [EnumMember(Value = "8011")]
        DoctorsAndPhysiciansNotElsewhereClassified = 8011, // Doctors and Physicians (Not Elsewhere Classified)
        [EnumMember(Value = "8021")]
        DentistsAndOrthodontists = 8021, // Dentists and Orthodontists
        [EnumMember(Value = "8031")]
        Osteopaths = 8031, // Osteopaths
        [EnumMember(Value = "8041")]
        Chiropractors = 8041, // Chiropractors
        [EnumMember(Value = "8042")]
        OptometristsAndOphthalmologists = 8042, // Optometrists and Ophthalmologists
        [EnumMember(Value = "8043")]
        OpticiansOpticiansGoodsAndEyeglasses = 8043, // Opticians, Opticians Goods and Eyeglasses
        [EnumMember(Value = "8044")]
        OpticiansOpticalGoodsAndEyeglassesNoLongerValidForFirstPresentments = 8044, // Opticians, Optical Goods, and Eyeglasses (no longer valid for first presentments)
        [EnumMember(Value = "8049")]
        PodiatristsAndChiropodists = 8049, // Podiatrists and Chiropodists
        [EnumMember(Value = "8050")]
        NursingAndPersonalCareFacilities = 8050, // Nursing and Personal Care Facilities
        [EnumMember(Value = "8062")]
        Hospitals = 8062, // Hospitals
        [EnumMember(Value = "8071")]
        MedicalAndDentalLaboratories = 8071, // Medical and Dental Laboratories
        [EnumMember(Value = "8099")]
        MedicalServicesAndHealthPractitionersNotElsewhereClassified = 8099, // Medical Services and Health Practitioners (Not Elsewhere Classified)
        [EnumMember(Value = "8111")]
        LegalServicesAndAttorneys = 8111, // Legal Services and Attorneys
        [EnumMember(Value = "8211")]
        ElementaryAndSecondarySchools = 8211, // Elementary and Secondary Schools
        [EnumMember(Value = "8220")]
        CollegesJuniorCollegesUniversitiesAndProfessionalSchools = 8220, // Colleges, Junior Colleges, Universities, and Professional Schools
        [EnumMember(Value = "8241")]
        CorrespondenceSchools = 8241, // Correspondence Schools
        [EnumMember(Value = "8244")]
        BusinessAndSecretarialSchools = 8244, // Business and Secretarial Schools
        [EnumMember(Value = "8249")]
        VocationalSchoolsAndTradeSchools = 8249, // Vocational Schools and Trade Schools
        [EnumMember(Value = "8299")]
        SchoolsAndEducationalServicesNotElsewhereClassified = 8299, // Schools and Educational Services ( Not Elsewhere Classified)
        [EnumMember(Value = "8351")]
        ChildCareServices = 8351, // Child Care Services
        [EnumMember(Value = "8398")]
        CharitableAndSocialServiceOrganizations = 8398, // Charitable and Social Service Organizations
        [EnumMember(Value = "8641")]
        CivicFraternalAndSocialAssociations = 8641, // Civic, Fraternal, and Social Associations
        [EnumMember(Value = "8651")]
        PoliticalOrganizations = 8651, // Political Organizations
        [EnumMember(Value = "8661")]
        ReligiousOrganizations = 8661, // Religious Organizations
        [EnumMember(Value = "8675")]
        AutomobileAssociations = 8675, // Automobile Associations
        [EnumMember(Value = "8699")]
        MembershipOrganizationsNotElsewhereClassified = 8699, // Membership Organizations ( Not Elsewhere Classified)
        [EnumMember(Value = "8734")]
        TestingLaboratoriesNonMedical = 8734, // Testing Laboratories ( non - medical)
        [EnumMember(Value = "8911")]
        ArchitecturalEngineeringAndSurveyingServices = 8911, // Architectural - Engineering and Surveying Services
        [EnumMember(Value = "8931")]
        AccountingAuditingAndBookkeepingServices = 8931, // Accounting, Auditing, and Bookkeeping Services
        [EnumMember(Value = "8999")]
        ProfessionalServicesNotElsewhereDefined = 8999, // Professional Services ( Not Elsewhere Defined)
        [EnumMember(Value = "9211")]
        CourtCostsIncludingAlimonyAndChildSupport = 9211, // Court Costs, including Alimony and Child Support
        [EnumMember(Value = "9222")]
        Fines = 9222, // Fines
        [EnumMember(Value = "9223")]
        BailAndBondPayments = 9223, // Bail and Bond Payments
        [EnumMember(Value = "9311")]
        TaxPayments = 9311, // Tax Payments
        [EnumMember(Value = "9399")]
        GovernmentServicesNotElsewhereClassified = 9399, // Government Services ( Not Elsewhere Classified)
        [EnumMember(Value = "9402")]
        PostalServicesGovernmentOnly = 9402, // Postal Services - Government Only
        [EnumMember(Value = "9405")]
        IntraGovernmentTransactions = 9405, // Intra - Government Transactions
        [EnumMember(Value = "9700")]
        AutomatedReferralServiceForVisaOnly = 9700, // Automated Referral Service (For Visa Only)
        [EnumMember(Value = "9701")]
        VisaCredentialServiceForVisaOnly = 9701, // Visa Credential Service ( For Visa Only)
        [EnumMember(Value = "9702")]
        GcasEmergencyServicesForVisaOnly = 9702, // GCAS Emergency Services ( For Visa Only)
        [EnumMember(Value = "9950")]
        IntraCompanyPurchasesForVisaOnly = 9950, // Intra - Company Purchases ( For Visa Only)
    }
}
